### ISSUE TITLE
Question about part segmentation code

### ISSUE THREAD

**Issue by Zhangyr2022** [xhanxu/Mamba3D#10]
感谢您们团队的杰出作品！请问目前的codebase中包含 part segmetation 的模型结构吗？谢谢！

**Comment by xhanxu** [comment]
Our current repository does not support part segmentation, but we follow the relevant code from Point-BERT and Point-MAE. You can easily adapt them here.

**Comment by Zhangyr2022** [comment]
> Our current repository does not support part segmentation, but we follow the relevant code from Point-BERT and Point-MAE. You can easily adapt them here.

OK, thanks!

**Comment by zzm666-ui** [comment]
> 感谢你们团队的杰出作品！请问目前的代码库中包含部分分割的模型结构吗？谢谢！

Excuse me, did you find the relevant part partition code?Thanks!
