### ISSUE TITLE
Question about K_Norm

### ISSUE THREAD

**Issue by Nero-XD** [xhanxu/Mamba3D#11]
每组点通过12层的Mamba3D Block时，LNP Block输入的center是相同的，每次进入K-Norm时都要求一次knn，得到这些center的3个临近点，对相同的center求knn过程重复了12次。
请问是我的理解有问题还是重复的KNN操作确实执行了12次？我实验之后发现knn操作占了Mamba3D Block里很大一部分时间，是否实际只用执行一次？

**Comment by xhanxu** [comment]
Yes, in fact, only one KNN is needed, and we perform KNN each time just for simplicity in implementation.
We welcome and appreciate any improvements you can make to the repo's code!

**Comment by Nero-XD** [comment]
感谢您的积极回复！
