### ISSUE TITLE
KeyError: 'Point_MAE is not in the models registry'

### ISSUE THREAD

**Issue by v-wewei** [xhanxu/Mamba3D#14]
bash script/run_pretrain.sh cause the error, could you please help to check the code?

**Comment by xhanxu** [comment]
My apologies, our code does not currently include pre-training code, but we have provided the pre-trained model weights. Moreover, we follow the pre-training code of `Point-MAE` and `Point-BERT`, which you can easily adapt to Mamba3D.

**Comment by v-wewei** [comment]
Okay, thanks for your answer. I am able to fix the error.
