### ISSUE TITLE
Hello, thank you for your excellent work, but I encountered some problems when studying your code. After I modified the code, the code automatically deleted my changes when it was run and restored to the original state. What is the cause of this problem? How can I solve this problem?

### ISSUE THREAD

**Issue by JennyWow111** [xhanxu/Mamba3D#7]
Hello, thank you for your excellent work, but I encountered some problems when studying your code. After I modified the code, the code automatically deleted my changes when it was run and restored to the original state. What is the cause of this problem? How can I solve this problem?

**Comment by xhanxu** [comment]
I didn't quite understand your question. Could you give a specific example, such as where the change was made?
Or perhaps it's because we have been continuously updating the code in the past few days. If you clone the code to your local environment, would the issue of automatic modification still occur?

**Comment by JennyWow111** [comment]
Before I run the code, the code looks like this
![7857c3053f91af07c8204de8caa7476](https://github.com/user-attachments/assets/d7c811ed-e63b-4b9b-a2fb-65d719bf282a)
After executing the run command, the code automatically deleted my print command
![image](https://github.com/user-attachments/assets/e56054cf-7fcb-4b1e-a7af-ecc1494062a7)

**Comment by JennyWow111** [comment]
I have cloned the code locally.

**Comment by JennyWow111** [comment]
Ah~ Sorry, I just noticed that the code has been updated several times yesterday. I cloned the new code and this problem no longer occurs. Sorry for taking up your valuable time.
