### ISSUE TITLE
Running on custom dataset

### ISSUE THREAD

**Issue by Inshu32** [xhanxu/Mamba3D#8]
Hi, 

Thanks for the amazing work ! Is it possible to run this on custom dataset ?
If yes, what will be the format of the training data. 

Thanks !

**Comment by xhanxu** [comment]
Absolutely, our model is adept at managing point cloud data originating from a variety of sources. For detailed instructions on the required data formats, kindly read the `DATASET.md` file and the data processing & loading scripts within the `datasets` directory.

Generally speaking, if you can preprocess the point cloud data into a `[B, N, 3]` tensor structure—where B denotes the batch size, N indicates the count of points, and 3 corresponds to the xyz coordinates—it will be straightforward to load this data into our model.
