### ISSUE TITLE
Questions about reproducibility

### ISSUE THREAD

**Issue by Nero-XD** [xhanxu/Mamba3D#9]
Hello, thank you for your excellent work, but when I started training Mamba3D from scratch, I achieved accuracies (w/o voting) of 91.91, 90.71, 91.15, and 91.77 on OBJ-BG, OBJ-ONLY, HARDEST, and MODELNET40, respectively. This is somewhat different from the 92.94, 92.08, 91.81, and 93.4 mentioned in your paper, especially on modelnet. May I ask if there are any other tips during training, and when can you release the pre training weights?
|     | obj_bg  | obj_only | hardest | modelnet |
|  ----  | ----  | ---- | ---- | ---- |
| result in paper  | 92.94 | 92.08 | 91.81 | 93.4 |
| my training result  | 91.91 | 90.71 | 91.15 | 91.77 |

**Comment by xhanxu** [comment]
Thank you for your interest in our work!

For the ScanObjectNN dataset, we have observed some variability in the results and are actively investigating the reasons. We suggest running the experiments multiple times, which should enable you to reach the results in the paper.

For the ModelNet40 dataset, please check if your data augmentation strategy aligns with the one used in the paper.

As for the pre-trained weights, we will try to release them within a few weeks. Please stay tuned!

**Comment by Nero-XD** [comment]
Thank you for your positive response. After checking, I found that the default data augmentation used in the code for training modelnet is _rotation_, while _scale&transformer_ is used in the paper. I am preparing to retrain on the modelnet dataset. Looking forward to updates of your repository!

**Comment by xhanxu** [comment]
Looking forward to seeing your updated results here!
We will improve the code to make it easier to reproduce the results.

**Comment by Nero-XD** [comment]
I'm back, after dozens of hours of training, I achieved a reproduction result of 93.72 on the ModelNet dataset. Your point cloud information processing work on MAMBA is really great, and I look forward to your future work!

**Comment by xhanxu** [comment]
We greatly appreciate your recognition of our work!

**Comment by xhanxu** [comment]
We have just released the pre-trained weights. Please check them out!
